-- company\sql\queries\

INSERT INTO DEPARTMENT (NAME) VALUES ('Engineering');       -- 2001
INSERT INTO DEPARTMENT (NAME) VALUES ('QA');                -- 2002
INSERT INTO DEPARTMENT (NAME) VALUES ('Accounting');        -- 2003
INSERT INTO DEPARTMENT (NAME) VALUES ('CAEngOtt');          -- 2004
INSERT INTO DEPARTMENT (NAME) VALUES ('USEngCal');          -- 2005
INSERT INTO DEPARTMENT (NAME) VALUES ('CADocOtt');          -- 2006
INSERT INTO DEPARTMENT (NAME) VALUES ('QA_East');           -- 2007
INSERT INTO DEPARTMENT (NAME) VALUES ('QANorth');           -- 2008


INSERT INTO PROJECT (NAME) VALUES ('Release1');             -- 3001
INSERT INTO PROJECT (NAME) VALUES ('Release2');             -- 3002
INSERT INTO PROJECT (NAME) VALUES ('Release3');             -- 3003
INSERT INTO PROJECT (NAME) VALUES ('Release4');             -- 3004


INSERT INTO PARKING_SPACE (LOT, LOCATION) VALUES (4711, 'VIP-area'); -- 9001
INSERT INTO PARKING_SPACE (LOT, LOCATION) VALUES (4321, 'disabled'); -- 9002
INSERT INTO PARKING_SPACE (LOT, LOCATION) VALUES (8765, 'children'); -- 9003
INSERT INTO PARKING_SPACE (LOT, LOCATION) VALUES (9999, 'retired' ); -- 9004


INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE, PARKING_SPACE_ID)
VALUES ('John',      'Pot',  2002, 'FullTimeEmployee', 9001);        -- 1001
INSERT INTO FULL_TIME_EMPLOYEE (ID, SALARY)
VALUES ( currval ('Employee_Sequence'), 5500 );

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE, PARKING_SPACE_ID )
VALUES ('Robert',    'Dil',  2002, 'FullTimeEmployee', 9002);       -- 1002
INSERT INTO FULL_TIME_EMPLOYEE (ID, SALARY)
VALUES ( currval ('Employee_Sequence'), 5300 );

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE, PARKING_SPACE_ID)
VALUES ('Peter',     'Pan',    2002, 'FullTimeEmployee', 9003);     -- 1003
INSERT INTO FULL_TIME_EMPLOYEE (ID, SALARY)
VALUES ( currval ('Employee_Sequence'), 50000 );

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE )
VALUES ('Frank',     'Stron',  2001, 'FullTimeEmployee');           -- 1004
INSERT INTO FULL_TIME_EMPLOYEE (ID, SALARY)
VALUES ( currval ('Employee_Sequence'), 51000 );

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE )
VALUES ('Scott',     'Oaks',  2001, 'FullTimeEmployee');            -- 1005
INSERT INTO FULL_TIME_EMPLOYEE (ID, SALARY)
VALUES ( currval ('Employee_Sequence'), 60000 );

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE )
VALUES ('Marcus',    'Rex',  NULL, 'FullTimeEmployee');             -- 1006
INSERT INTO FULL_TIME_EMPLOYEE (ID, SALARY)
VALUES ( currval ('Employee_Sequence'), 35000 );

-------------------------------------------------------------------

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE )
VALUES ('Joan',      'Oak',  2001, 'PartTimeEmployee');             -- 1007
INSERT INTO PART_TIME_EMPLOYEE (ID, HOURLYRATE)
VALUES ( currval ('Employee_Sequence'), 5.9 );

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE )
VALUES ('Sarah',     'Woe',  2001, 'PartTimeEmployee');             -- 1008
INSERT INTO PART_TIME_EMPLOYEE (ID, HOURLYRATE)
VALUES ( currval ('Employee_Sequence'), 5.2 );

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE )
VALUES ('Sue',       'Zip',   2001, 'PartTimeEmployee');            -- 1009
INSERT INTO PART_TIME_EMPLOYEE (ID, HOURLYRATE)
VALUES ( currval ('Employee_Sequence'), 62 );

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE )
VALUES ('Stephanie', 'Lur',  2001, 'PartTimeEmployee');             -- 1010
INSERT INTO PART_TIME_EMPLOYEE (ID, HOURLYRATE)
VALUES ( currval ('Employee_Sequence'), 54 );


INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE )
VALUES ('Jennifer',  'Jane', 2008, 'PartTimeEmployee');             -- 1011
INSERT INTO PART_TIME_EMPLOYEE (ID, HOURLYRATE)
VALUES ( currval ('Employee_Sequence'), 55 );

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, DEPARTMENT_ID, DTYPE )
VALUES ('Lizzy',  'Lazy', 2008, 'PartTimeEmployee');                -- 1012
INSERT INTO PART_TIME_EMPLOYEE (ID, HOURLYRATE)
VALUES ( currval ('Employee_Sequence'), 35 );




INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1001, 3001);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1002, 3002);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1002, 3003);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1003, 3001);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1003, 3002);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1003, 3003);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1004, 3001);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1005, 3002);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1005, 3003);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1006, 3001);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1006, 3002);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1007, 3003);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1008, 3001);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1008, 3002);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1009, 3003);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1009, 3001);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1010, 3001);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1010, 3002);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1010, 3003);

INSERT INTO EMPLOYEE_PROJECT (EMPLOYEES_ID, PROJECTS_ID) VALUES (1011, 3004);

