CREATE TABLE public.CUSTOMER
(
    CUSTOMER_NUMBER INT PRIMARY KEY,
    NAME VARCHAR,
    ADDRESS VARCHAR
);

CREATE TABLE public.TICKET
(
    TICKET_NUMBER INT PRIMARY KEY,
    DATE DATE,
    FK_CUSTOMER_NUMBER VARCHAR,
    FK_CONTINGENT_ID INT,
    FK_PLACE_NUMBER INT,
    FK_PLACE_ROW INT,
    FK_PLACE_SECTION INT
);

CREATE TABLE public.PLACE
(
    PLACE_NUMBER INT,
    PLACE_ROW INT,
    PLACE_SECTION INT,
    FK_CATEGORY_DESCRIPTION VARCHAR,
    FK_STADION_ID INT,
    FK_TICKET_NUMBER INT,
    PRIMARY KEY (PLACE_NUMBER,PLACE_ROW,PLACE_SECTION)
);

CREATE TABLE public.CATEGORY
(
      DESCRIPTION VARCHAR PRIMARY KEY,
      PRICE INT
);

CREATE TABLE public.CONTINGENT
(
      ID int PRIMARY KEY,
      QUANTITY INT,
      FK_MATCH_DATE DATE ,
      FK_MATCH_TIME TIME
);