CREATE TABLE public.TEAM
(
    pk_id INT PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE public.TEAM_MATCH
(
    pk_id INT PRIMARY KEY,
    fk_team_a_id VARCHAR NOT NULL,
    fk_team_b_id VARCHAR NOT NULL,
    fk_match_date DATE NOT NULL,
    fk_match_time TIME NOT NULL
);

CREATE TABLE public.MATCH
(
    pk_date DATE,
    pk_time TIME,
    stadium VARCHAR NOT NULL,
    PRIMARY KEY(pk_date,pk_time)
);

CREATE TABLE public.STADIUM
(
    pk_id INT PRIMARY KEY NOT NULL,
    location VARCHAR NOT NULL,
    total_capacity VARCHAR NOT NULL
);

CREATE TABLE public.CUSTOMER
(
    CUSTOMER_NUMBER INT PRIMARY KEY,
    NAME VARCHAR,
    ADDRESS VARCHAR
);

CREATE TABLE public.TICKET
(
    TICKET_NUMBER INT PRIMARY KEY,
    DATE DATE,
    FK_CUSTOMER_NUMBER VARCHAR,
    FK_CONTINGENT_ID INT,
    FK_PLACE_NUMBER INT,
    FK_PLACE_ROW INT,
    FK_PLACE_SECTION INT
);

CREATE TABLE public.CATEGORY
(
      DESCRIPTION VARCHAR PRIMARY KEY,
      PRICE INT
);

CREATE TABLE public.CONTINGENT
(
      ID int PRIMARY KEY,
      QUANTITY INT,
      FK_MATCH_DATE DATE ,
      FK_MATCH_TIME TIME
);

CREATE TABLE public.PLACE
(
    PLACE_NUMBER INT,
    PLACE_ROW INT,
    PLACE_SECTION INT,
    FK_CATEGORY_DESCRIPTION VARCHAR,
    FK_STADION_ID INT,
    FK_TICKET_NUMBER INT,
    PRIMARY KEY (PLACE_NUMBER,PLACE_ROW,PLACE_SECTION)
);

CREATE TABLE public.WITH_TRACK
(
    fk_stadium_id INT NOT NULL,
    number_tracks INT
);

CREATE TABLE public.WITHOUT_TRACK
(
    fk_stadium_id INT NOT NULL
);