DROP TABLE category CASCADE;
DROP TABLE contingent CASCADE;
DROP TABLE customer CASCADE;
DROP TABLE match CASCADE;
DROP TABLE place CASCADE;
DROP TABLE stadium CASCADE;
DROP TABLE team CASCADE;
DROP TABLE team_match CASCADE;
DROP TABLE with_track CASCADE;
DROP TABLE without_track CASCADE;
DROP TABLE ticket CASCADE;


