-- company\PK-compound\sql

CREATE TABLE PKCompound.EMPLOYEE (
    COUNTRY     VARCHAR,
    ID          INTEGER,
    FIRSTNAME   VARCHAR,
    LASTNAME    VARCHAR
);

ALTER TABLE PKCompound.EMPLOYEE
    ADD CONSTRAINT pk_EMPLOYEE PRIMARY KEY (COUNTRY, ID);

